
[types]

	[types.leaves_type]

		[types.leaves_type.nethers_exoticism]
			jaboticaba = true

		[types.leaves_type.vinery]
			grapevine = true
			cherry = true

		[types.leaves_type.maidensmerrymaking]
			pine = true

		[types.leaves_type.abundant_atmosphere]
			ash = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.byg]
			araucaria = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			joshua = true
			ripe_joshua = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			palo_verde = true
			pink_cherry = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			ripe_orchard = true
			silver_maple = true
			green_apple_skyris = true
			white_cherry = true
			yellow_birch = true
			yellow_spruce = true
			withering_oak = true
			flowering_nightshade = true
			firecracker = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.leaves_type.blue_skies]
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true
			crescent_fruit = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.nethers_exoticism]
			jabuticaba = true
			ramboutan = true

		[types.wood_type.gardens_of_the_dead]
			soulblight = true

		[types.wood_type.twigs]
			bamboo = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			blossom = true

		[types.wood_type.vinery]
			cherry = true

		[types.wood_type.maidensmerrymaking]
			pine = true
			exposed_pine = true
			weathered_pine = true
			aged_pine = true
			preserved_pine = true
			preserved_exposed_pine = true
			preserved_weathered_pine = true
			preserved_aged_pine = true

		[types.wood_type.abundant_atmosphere]
			ash = true

		[types.wood_type.byg]
			aspen = true
			baobab = true
			blue_enchanted = true
			bulbis = true
			cherry = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			imparius = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			sythian = true

		[types.wood_type.blue_skies]
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

	[types.cut_blocK_type]

		[types.cut_blocK_type.nethers_exoticism]
			jaboticaba = true
			ramboutan = true

		[types.cut_blocK_type.stalwart_dungeons]
			soul_bricks = true
			soul_tiles = true
			nether_bricks_and_netherrack = true
			nether_bricks_and_soul_sand = true
			purpur_bricks = true
			purpur_bricks_and_endstone = true

		[types.cut_blocK_type.vinery]
			cherry = true
			loam = true
			coarse_dirt = true
			dirt = true
			grass = true

		[types.cut_blocK_type.supplementaries]
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_blocK_type.maidensmerrymaking]
			pine = true
			exposed_pine = true
			weathered_pine = true
			aged_pine = true

		[types.cut_blocK_type.geode]
			smooth_end_stone = true

		[types.cut_blocK_type.unusualend]
			raw_purpur_block = true
			polished_purpur = true
			polished_purpur_tiles = true
			chorus_nest = true
			stripped_chorus_nest = true
			chorus_nest_mosaic = true

		[types.cut_blocK_type.abundant_atmosphere]
			ash = true
			polished_calcite = true
			polished_dripstone = true

		[types.cut_blocK_type.immersive_weathering]
			mossy_stone = true
			snowy_stone = true
			snowy_cobblestone = true
			sandy_stone = true
			sandy_cobblestone = true
			cut_iron = true
			exposed_cut_iron = true
			weathered_cut_iron = true
			rusted_cut_iron = true
			waxed_cut_iron = true
			waxed_exposed_cut_iron = true
			waxed_weathered_cut_iron = true
			waxed_rusted_cut_iron = true
			plate_iron = true
			exposed_plate_iron = true
			weathered_plate_iron = true
			rusted_plate_iron = true
			waxed_plate_iron = true
			waxed_exposed_plate_iron = true
			waxed_weathered_plate_iron = true
			waxed_rusted_plate_iron = true
			charred = true

		[types.cut_blocK_type.ecologics]
			coconut = true
			walnut = true
			azalea = true
			flowering_azalea = true

		[types.cut_blocK_type.byg]
			cattail_thatch = true
			purpur_stone = true
			ether_stone = true
			cobbled_ether_stone = true
			carved_ether_stone = true
			chiseled_therium = true
			shiny_chiseled_therium = true
			cryptic_stone = true
			chiseled_fungal_imparius = true
			windswept_sandstone = true
			chiseled_windswept_sandstone = true
			cut_windswept_sandstone = true
			smooth_windswept_sandstone = true
			dacite = true
			dacite_cobblestone = true
			dacite_tile = true
			red_rock = true
			mossy_stone = true
			rocky_stone = true
			travertine = true
			polished_travertine = true
			chiseled_travertine = true
			scoria_stone = true
			scoria_cobblestone = true
			soapstone = true
			polished_soapstone = true
			soapstone_tile = true
			aspen = true
			baobab = true
			blue_enchanted = true
			bulbis = true
			cherry = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			imparius = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			sythian = true
			embur = true

		[types.cut_blocK_type.sculked]
			smooth_deepslate = true
			cut_echo_copper_block = true
			sculked_bone_tile = true
			vibestone = true
			polished_vibestone = true

		[types.cut_blocK_type.blue_skies]
			nature_stone = true
			glowing_nature_stone = true
			nature_stonebrick = true
			glowing_nature_stonebrick = true
			poison_stone = true
			glowing_poison_stone = true
			poison_stonebrick = true
			rough_poison_stonebrick = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			cherry = true
			crystallized = true
			turquoise_stone = true
			turquoise_cobblestone = true
			mossy_turquoise_cobblestone = true
			turquoise_stonebrick = true
			mossy_turquoise_stonebrick = true
			cracked_turquoise_stonebrick = true
			midnight_sandstone = true
			smooth_midnight_sandstone = true
			brumble = true
			polished_brumble = true
			taratite = true
			polished_taratite = true
			rimestone = true
			polished_rimestone = true
			lunar_stone = true
			lunar_cobblestone = true
			mossy_lunar_cobblestone = true
			lunar_stonebrick = true
			mossy_lunar_stonebrick = true
			cracked_lunar_stonebrick = true
			crystal_sandstone = true
			smooth_crystal_sandstone = true
			cut_midnight_sandstone = true
			cut_crystal_sandstone = true
			umber = true
			polished_umber = true
			cinderstone = true
			polished_cinderstone = true

		[types.cut_blocK_type.galosphere]
			smooth_amethyst = true
			smooth_allurite = true
			smooth_lumiere = true

		[types.cut_blocK_type.twigs]
			bamboo_thatch = true
			stripped_bamboo = true
			polished_amethyst = true
			tuff = true
			polished_tuff = true
			calcite = true
			polished_calcite = true
			rhyolite = true
			polished_rhyolite = true
			schist = true
			polished_schist = true
			bloodstone = true
			polished_bloodstone = true

		[types.cut_blocK_type.bygonenether]
			withered_blackstone = true
			cracked_withered_blackstone = true

		[types.cut_blocK_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.cut_blocK_type.dustrial_decor]
			sheet_metal_plating = true
			sheet_metal_treading = true
			rusty_sheet_metal_plating = true
			rusty_sheet_metal_treading = true
			smooth_cardboard = true

		[types.cut_blocK_type.cataclysm]
			polished_end_stone = true
			chorus = true

		[types.cut_blocK_type.deeperdarker]
			echo = true
			sculk_stone = true
			cobbled_sculk_stone = true
			polished_sculk_stone = true
			smooth_sculk_stone = true
			cut_sculk_stone = true
			gloomslate = true
			cobbled_gloomslate = true
			polished_gloomslate = true
			smooth_gloomslate = true
			cut_gloomslate = true

		[types.cut_blocK_type.bambooeverything]
			bamboo = true

		[types.cut_blocK_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true
			red_mushroom_brick = true
			brown_mushroom_brick = true
			purple_glowshroom_brick = true
			green_glowshroom_brick = true
			orange_glowshroom_brick = true
			glowshroom_stem_brick = true
			mushroom_stem_brick = true
			blighted_cobblestone = true
			blighted_stone_bricks = true
			dried_peat_bricks = true
			mesmerite = true
			polished_mesmerite = true

		[types.cut_blocK_type.neapolitan]
			frond_thatch = true

		[types.cut_blocK_type.frozenup]
			cut_ice = true

		[types.cut_blocK_type.gardens_of_the_dead]
			soulblight = true
			whistlecane = true

		[types.cut_blocK_type.snowyspirit]
			gingerbread = true

		[types.cut_blocK_type.quark]
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true
			blossom_planks = true
			iron_plate = true
			rusty_iron_plate = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			duskbound_block = true
			permafrost = true
			permafrost_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			azalea_planks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			midori_block = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

	[entries.wood_type]

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.another_furniture]
			shelf = true
			shutter = true
			planter_box = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.woodworks]
			boards = true
			beehive = true
			bookshelf = true
			ladder = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

